### ISSUE TITLE
quiet mode file is never closed

### ISSUE THREAD

**Issue by sigma67** [datafolklabs/cement#653] opened 2023-06-07 15:27 UTC
**System Information**

- Cement Version: 3.0.8
- Python Version: any
- Operating System and Version: any

**Steps to Reproduce (Bugs Only)**

- set PYTHONWARNINGS=error
- run any cement app in quiet mode
- on exit, an Exception will be raised:

```
ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>
```

Relevant lines to fix (files are never closed): https://github.com/datafolklabs/cement/blob/91bc3424c4bc3d46cba0c4d36eef493d7aa85635/cement/core/foundation.py#L1136-L1149

**Comment by derks** [comment] 2023-12-27 01:54
@sigma67 I can't reproduce this... tried Python 3.8, and 3.12:

*myapp.py*

```
from cement import App

with App('myapp') as app:
    app.run()
    print('KAPLA')
```


Result:

```
/src/cement/core/foundation.py:762: DeprecationWarning: App.Meta.framework_logging will be changed or removed in Cement v3.2.0. See: https://docs.builtoncement.com/release-information/deprecations#3.0.8-2
  deprecate('3.0.8-2')
KAPLA

|> cement-py38 <| tmp # python test.py --quiet
/src/cement/core/foundation.py:762: DeprecationWarning: App.Meta.framework_logging will be changed or removed in Cement v3.2.0. See: https://docs.builtoncement.com/release-information/deprecations#3.0.8-2
  deprecate('3.0.8-2')

|> cement-py38 <| tmp # echo $?
0
```

Setting `PYTHONWARNINGS=once` or `error`, niether produce the `io.TextIOWrapper` warning.

**Comment by sigma67** [comment] 2023-12-27 14:32
Change l.3 to

```python
with App('myapp', argv=["--quiet"]) as app:
```

Place it in a script file. Run `pytest testfile.py`. 

Remove `--quiet` flag, observe the warning disappearing.

The warning seems to only happen when it's run inside a subprocess. I presume since otherwise nobody's there to observe the unclosed file.

**Comment by sigma67** [comment] 2023-12-27 14:40
Minimal reproduction:

``` python
import pytest

from cement import App

def test_cement():
    with pytest.raises(SystemExit):
        with App('myapp', argv=["--quiet"]) as app:
            app.run()
```

`PYTHONWARNINGS=error pytest testfile.py`

Passes without `--quiet`.

**Comment by derks** [comment] 2024-01-02 00:18
@sigma67 appreciate the minimal example, I can see and reproduce it now:

```
|> cement-py312 <| tmp # pytest test.py
==================================================== test session starts ====================================================
platform linux -- Python 3.12.1, pytest-7.4.3, pluggy-1.3.0
rootdir: /src
configfile: setup.cfg
plugins: cov-4.1.0
collected 2 items

test.py .F                                                                                                            [100%]

========================================================= FAILURES ==========================================================
_____________________________________________________ test_cement_quiet _____________________________________________________

    def test_cement_quiet():
>       with pytest.raises(SystemExit):
E       Failed: DID NOT RAISE <class 'SystemExit'>

test.py:13: Failed
===================================================== warnings summary ======================================================
tmp/test.py::test_cement
tmp/test.py::test_cement_quiet
  /src/cement/core/foundation.py:762: DeprecationWarning: App.Meta.framework_logging will be changed or removed in Cement v3.2.0. See: https://docs.builtoncement.com/release-information/deprecations#3.0.8-2
    deprecate('3.0.8-2')

tmp/test.py::test_cement_quiet
  /usr/local/lib/python3.12/site-packages/_pytest/capture.py:391: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>
    setattr(sys, self.name, self._old)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================== short test summary info ==================================================
FAILED test.py::test_cement_quiet - Failed: DID NOT RAISE <class 'SystemExit'>
========================================== 1 failed, 1 passed, 3 warnings in 0.17s ==========================================
```

**Comment by derks** [comment] 2024-01-02 00:31
@sigma67 this is resolved in `main`, and will be deployed with `stable/3.0.10`. Would love if you could test/verify if you have a moment.

**Comment by derks** [comment] 2024-01-02 00:33
Actually... retracting that, sorry... the `ResourceWarning` is resolved however the Pytest example still fails when using `--quiet`...

```
|> cement-py312 <| tmp # pytest test.py
==================================================== test session starts ====================================================
platform linux -- Python 3.12.1, pytest-7.4.3, pluggy-1.3.0
rootdir: /src
configfile: setup.cfg
plugins: cov-4.1.0
collected 2 items

test.py .F                                                                                                            [100%]

========================================================= FAILURES ==========================================================
_____________________________________________________ test_cement_quiet _____________________________________________________

    def test_cement_quiet():
>       with pytest.raises(SystemExit):
E       Failed: DID NOT RAISE <class 'SystemExit'>

test.py:13: Failed
===================================================== warnings summary ======================================================
tmp/test.py::test_cement
tmp/test.py::test_cement_quiet
  /src/cement/core/foundation.py:762: DeprecationWarning: App.Meta.framework_logging will be changed or removed in Cement v3.2.0. See: https://docs.builtoncement.com/release-information/deprecations#3.0.8-2
    deprecate('3.0.8-2')

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================== short test summary info ==================================================
FAILED test.py::test_cement_quiet - Failed: DID NOT RAISE <class 'SystemExit'>
========================================== 1 failed, 1 passed, 2 warnings in 0.22s ==========================================
```

Odd.

**Comment by derks** [comment] 2024-01-02 02:31
OK, I think there was just some mixups with the example...  1. `App.Meta.exit_on_close` is default to `False`, so SystemExit shouldn't actually have been raised... but because there was no `argv=[]` passed in my modified example (without quiet) it was using the actual sys.argv and failing:

```
usage: myapp [-h] [-d] [-q]
myapp: error: unrecognized arguments: test.py
```

Which produced a SystemExit.  Regardless I've modified the fix slightly and the following pass:

```

import pytest

from cement import App

def test_cement_exit_on_close():
    with pytest.raises(SystemExit):
        with App('myapp',argv=[], exit_on_close=True) as app:
            app.run()


def test_cement_quiet_exit_on_close():
    with pytest.raises(SystemExit):
        with App('myapp', argv=["--quiet"], exit_on_close=True) as app:
            app.run()

def test_cement():
    with App('myapp', argv=[]) as app:
        print(app._meta.exit_on_close)
        app.run()


def test_cement_quiet():
    with App('myapp', argv=["--quiet"]) as app:
        app.run()
```


Added this to `main` along with some additional tweaks discovered while testing.

**Closed by derks** 2024-01-02 02:31 UTC
Labels: bug, stable/3.0.x

**Comment by sigma67** [comment] 2024-01-02 08:10
Thanks for this! ❤️
