### ISSUE TITLE
MemoryError during 'cement generate project'

### ISSUE THREAD

**Issue by przemekkot** [datafolklabs/cement#531] opened 2018-08-28 08:10 UTC
Well I run command to generate project and it fails due to MemeryError. 

**System Information**

- Cement Version: 3.0.0
- Python Version: 3.6.5 (32bit)
- Operating System and Version: Platform Windows-10-10.0.15063-SP0

**Steps to Reproduce (Bugs Only)**

- Step 1
  Run 'cement generate project NAME'

**Error message**

```
INFO: Generating cement project in cem
App Label [myapp]: cem
App Name [My Application]: cem
App Class Name [MyApp]: cem
App Description [MyApp Does Amazing Things!]: cem
Creator Name [John Doe]: cem
Creator Email [john.doe@example.com]:
Project URL [https://github.com/johndoe/myapp/]: ""
License [unlicensed]:
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36-32\Scripts\cement.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\cement\cli\main.py", line 40, in main
    app.run()
  File "c:\program files (x86)\python36-32\lib\site-packages\cement\core\foundation.py", line 916, in run
    return_val = self.controller._dispatch()
  File "c:\program files (x86)\python36-32\lib\site-packages\cement\ext\ext_argparse.py", line 806, in _dispatch
    return func()
  File "c:\program files (x86)\python36-32\lib\site-packages\cement\ext\ext_generate.py", line 129, in _default
    self._generate(source, dest)
  File "c:\program files (x86)\python36-32\lib\site-packages\cement\ext\ext_generate.py", line 101, in _generate
    exclude=exclude_list)
  File "c:\program files (x86)\python36-32\lib\site-packages\cement\core\template.py", line 246, in copy
    new_file = re.sub(src, '', self.render(_file, data))
  File "c:\program files (x86)\python36-32\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "c:\program files (x86)\python36-32\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "c:\program files (x86)\python36-32\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "c:\program files (x86)\python36-32\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "c:\program files (x86)\python36-32\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "c:\program files (x86)\python36-32\lib\sre_parse.py", line 503, in _parse
    subpatternappend(code)
  File "c:\program files (x86)\python36-32\lib\sre_parse.py", line 172, in append
    self.data.append(code)
MemoryError
```

**Comment by derks** [comment] 2018-08-29 17:07
I saw a similar issue when testing windows but couldn't reproduce it enough to figure out the issues.  If it is possible to run Docker on Windows 10 (I think it is now), you could do that as a workaround:

```
$ docker run -it -v /path/to/projects:/projects datafolklabs/cement:3 generate project /projects/myapp
```

**Comment by przemekkot** [comment] 2018-08-30 09:55
Thanks for the idea, but sadly I work in a corporate environment and this is impossible. I copy the todo template and work on it as work around.

**Comment by derks** [comment] 2018-10-31 19:21
@przemekkot I just pushed a fix for this to `master`.  Any chance you could test/verify it?

**Comment by canwaf** [comment] 2018-11-02 10:22
@derks, once this makes it way to the conda-forge, I'll validate. I'm also in a corporate environment, so limited in where I can source things.

**Closed** 2018-11-06 17:02 UTC
Labels: bug
