### ISSUE TITLE
inconsistent behaviour when using colorlog feature of cement 2.6

### ISSUE THREAD

**Issue by rjdp** [datafolklabs/cement#314] opened 2015-06-11 09:09 UTC
when using colorlog(cement2.6) log messages are not written to the 'log file'(mentioned in the config) when 'level' is set to 'debug' but when level is set to other than 'debug' , messages are written to log file as expected .

**Comment by derks** [comment] 2015-06-11 16:51
@rjdp thanks for the report. Will look at this today.

**Comment by rjdp** [comment] 2015-06-12 05:10
@derks  ... also when it(colorlog) does write to log file , the log entries don't have the color info / the log messages aren't color coded .

**Comment by derks** [comment] 2015-06-12 17:34
@rjdp sorry I didn't get to this yesterday, but will be checking it out now.  Not embedding color codes in the log files was by design, as I did not think that would be anyones preference.  That said, I'll make sure that bit is configurable so that you can enable it if you wish.

**Comment by derks** [comment] 2015-06-12 17:41
Confirmed that debug logging is broken in `colorlog`:

```
2015-06-12 12:40:09,473 (DEBUG) myapp : logging initialized for 'myapp' using ColorLogHandler
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 978, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 568, in format
    s = self.formatMessage(record)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 537, in formatMessage
    return self._style.format(record)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 381, in format
    return self._fmt % record.__dict__
KeyError: 'log_color'
Call stack:
  File "myapp.py", line 40, in <module>
    with MyApp() as app:
  File "/Users/derks/Development/cement/cement/core/foundation.py", line 772, in __enter__
    self.setup()
  File "/Users/derks/Development/cement/cement/core/foundation.py", line 744, in setup
    self._setup_log_handler()
  File "/Users/derks/Development/cement/cement/core/foundation.py", line 1092, in _setup_log_handler
    self.log = self._resolve_handler('log', self._meta.log_handler)
  File "/Users/derks/Development/cement/cement/core/foundation.py", line 1009, in _resolve_handler
    han._setup(self)
  File "/Users/derks/Development/cement/cement/ext/ext_logging.py", line 128, in _setup
    (self._meta.namespace, self.__class__.__name__))
  File "/Users/derks/Development/cement/cement/ext/ext_logging.py", line 311, in debug
    self.backend.debug(msg, **kwargs)
Message: "logging initialized for 'myapp' using ColorLogHandler"
Arguments: ()
```

**Comment by derks** [comment] 2015-06-12 19:23
This is resolved in `master` and `stable/2.6.x` branches.  Will push out Cement 2.6.2 Stable relatively soon.  The default for log files is to **not** colorize them, however you can override this behavior with the meta option `colorize_log_files = True`.  For example:

```python
from cement.core.foundation import CementApp
from cement.ext.ext_colorlog import ColorLogHandler

class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        extensions = ['colorlog']
        log_handler = ColorLogHandler(colorize_log_files=True)
```

Please let me know if you see any other issues, and thanks for helping make Cement better!

**Comment by rjdp** [comment] 2015-06-12 20:20
thanks !

**Comment by derks** [comment] 2015-06-14 00:44
Note to self: Extension should support `colorize_file_log` and `colorize_console_log` via the config section `[log.colorlog]` as that is a per-user preference, and shouldn't be hard-coded by the app developer in `Meta`.

**Comment by harshadyeola** [comment] 2015-06-15 11:50
@derks 
May i know the release time for this fix?

**Comment by derks** [comment] 2015-06-15 16:17
Will plan on getting Cement 2.6.2 out this week.

**Closed** 2015-06-22 19:23 UTC
Labels: bug, dev/2.7.x, stable/2.6.x

**Comment by derks** [comment] 2015-06-22 19:39
@harshadyeola just release Cement 2.6.2, which includes this fix.
