### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by yurivict** [datafolklabs/cement#645] opened 2022-10-20 04:24 UTC
```
byte-compiling /disk-samsung/freebsd-ports/devel/py-cement/work-py39/stage/usr/local/lib/python3.9/site-packages/cement/core/deprecations.py to deprecations.cpython-39.pyc
writing byte-compilation script '/tmp/tmpkrx8hlza.py'
/usr/local/bin/python3.9 /tmp/tmpkrx8hlza.py
  File "/usr/local/lib/python3.9/site-packages/cement/cli/templates/generate/extension/ext_{{ label }}.py", line 6
    def {{ label }}_pre_run_hook(app):
        ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.9/site-packages/cement/cli/templates/generate/plugin/{{ label }}/controllers/{{ label }}.py", line 5
    class {{ class_name }}(Controller):
          ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.9/site-packages/cement/cli/templates/generate/plugin/{{ label }}/__init__.py", line 3
    from .controllers.{{ label }} import {{ class_name }}
                      ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.9/site-packages/cement/cli/templates/generate/project/{{ label }}/main.py", line 4
    from .core.exc import {{ class_name }}Error
                          ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.9/site-packages/cement/cli/templates/generate/project/{{ label }}/core/exc.py", line 2
    class {{ class_name }}Error(Exception):
          ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.9/site-packages/cement/cli/templates/generate/project/setup.py", line 3
    from {{ label }}.core.version import get_version
         ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.9/site-packages/cement/cli/templates/generate/project/tests/test_{{ label }}.py", line 3
    from {{ label }}.main import {{ class_name }}Test
         ^
SyntaxError: invalid syntax
```

Version: 3.0.8
Python-3.9
FreeBSD 13.1 STABLE

**Comment by derks** [comment] 2022-11-03 15:31
@yurivict thank you for the submission. This is a duplicate of Issue #633. Please add comments there if you have suggestions on how to avoid this (help wanted).

**Closed by derks** 2022-11-03 15:31 UTC
