### ISSUE TITLE
Quick Start Example Not Working

### ISSUE THREAD

**Issue by jtpereyda** [datafolklabs/cement#443] opened 2017-04-23 00:17 UTC
Running this example from [quick start](http://cement.readthedocs.io/en/latest/dev/quickstart/):
```python
from cement.core.foundation import CementApp
from cement.core import hook
from cement.utils.misc import init_defaults

# define our default configuration options
defaults = init_defaults('myapp')
defaults['myapp']['debug'] = False
defaults['myapp']['some_param'] = 'some value'

# define any hook functions here
def my_cleanup_hook(app):
    pass

# define the application class
class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        config_defaults = defaults
        extensions = ['daemon', 'memcached', 'json', 'yaml']
        hooks = [
            ('pre_close', my_cleanup_hook),
        ]

with MyApp() as app:
    # add arguments to the parser
    app.args.add_argument('-f', '--foo', action='store', metavar='STR',
                          help='the notorious foo option')

    # log stuff
    app.log.debug("About to run my myapp application!")

    # run the application
    app.run()

    # continue with additional application logic
    if app.pargs.foo:
        app.log.info("Received option: foo => %s" % app.pargs.foo)
```
with Python 3.5.2, I get this output:
```
>python3 demo-app.py
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\cement\core\extension.py", line 145, in load_extension
    __import__(ext_module, globals(), locals(), [], 0)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\cement\ext\ext_daemon.py", line 163, in <module>
    import pwd
ImportError: No module named 'pwd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo-app.py", line 23, in <module>
    with MyApp() as app:
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\cement\core\foundation.py", line 1494, in __enter__
    self.setup()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\cement\core\foundation.py", line 846, in setup
    self._setup_extension_handler()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\cement\core\foundation.py", line 1219, in _setup_extension_handler
    self.ext.load_extensions(self._meta.extensions)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\cement\core\extension.py", line 166, in load_extensions
    self.load_extension(ext)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\cement\core\extension.py", line 154, in load_extension
    raise exc.FrameworkError(e.args[0])
cement.core.exc.FrameworkError: No module named 'pwd'
```
With Python 2.7.12:
```
>python demo-app.py
Traceback (most recent call last):
  File "demo-app.py", line 24, in <module>
    with MyApp() as app:
  File "C:\Python27\lib\site-packages\cement\core\foundation.py", line 1494, in __enter__
    self.setup()
  File "C:\Python27\lib\site-packages\cement\core\foundation.py", line 846, in setup
    self._setup_extension_handler()
  File "C:\Python27\lib\site-packages\cement\core\foundation.py", line 1219, in _setup_extension_handler
    self.ext.load_extensions(self._meta.extensions)
  File "C:\Python27\lib\site-packages\cement\core\extension.py", line 166, in load_extensions
    self.load_extension(ext)
  File "C:\Python27\lib\site-packages\cement\core\extension.py", line 154, in load_extension
    raise exc.FrameworkError(e.args[0])
cement.core.exc.FrameworkError: No module named pwd
```
I can run some other cement apps though so I'm not sure what to change.

Cement version is 2.10.2

**Comment by jtpereyda** [comment] 2017-04-23 00:28
When I remove the extensions line it seems to work again. I removed the extensions one by one but I needed to take them all out for it to start working...

**Comment by derks** [comment] 2017-04-26 16:55
@jtpereyda the issue is in the `daemon` extension, though it isn't a bug necessarily because the doc does state it's only available on Unix/Linux:

That said, it was a poor choice to use that extension, or anything else that isn't crossplatform compatible in the quickstart, so will label this as a bug for the doc.

On that note, I will also create another issue to get the `daemon` extension cross-platform to atleast run on macOS as that should be relatively doable and to be honest, I hadn't realized (or remembered) that it wasn't macOS compatible.

**Comment by samlikins** [comment] 2018-01-10 04:44
@derks I've created a PR to change the QS docs to correct this issue, let me know if I should make any further modifications to it before it's merged.

**Closed** 2018-01-17 05:29 UTC
Labels: bug, chore, dev/2.11.x, doc, low-hanging-fruit, portland, stable/2.10.x
